### PR TITLE
"8.x-2.x >  8.2.0

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- Automated pull request created via HAL 9000.  See changes below for details.

# Review By (Date)
- As soon as possible

The following changes since commit 07fb75892dfa1912b358b8a3f448fc1c3c281e8c:

  Merge pull request #7 from SU-SWS/8.1.0-release (2019-10-30 15:19:55 -0700)

are available in the Git repository at:

  ./ 

for you to fetch changes up to 2bbfbf915aab96000ad0ad5211e7a6f374a7618f:

  8.1.1 (2020-05-15 10:39:44 -0600)

----------------------------------------------------------------
Ian Monroe (2):
      D8CORE-1644: Dev branch workflow
      8.1.1

Sherakama (2):
      back to dev.
      Update nobots.info.yml (#8)

 .github/workflows/release.yml | 18 ++++++++++++++++++
 CHANGELOG.txt                 |  7 +++++++
 README.md                     | 16 ++++++++++++++++
 nobots.info.yml               |  7 +++----
 4 files changed, 44 insertions(+), 4 deletions(-)
 create mode 100644 .github/workflows/release.yml"

### CODE REVIEW

**Comment by sherakama** [comment]
@imonroe  8.x-2.x to 8.1.1?

**Comment by imonroe** [comment]
> @imonroe 8.x-2.x to 8.1.1?

Ah, the last tagged version was 8.1.0, and this was a patch.  

Should this become 8.2.0?

**Comment by jbickar** [comment]
We had a conversation about this and I believe that we decided it was a backwards-incompatible change and that it should be a minor version bump.

**Comment by imonroe** [comment]
Ok, the branch name is wrong, but the commits are right.  This should bump it to 8.2.0 via the github actions upon merge. 

I think this is the first time we've tried the github actions for anything other than a patch increment.

**Review by sherakama — APPROVED** [review]

**Pull request merged**
